### PR TITLE
allow route options:defaults in uri generation

### PR DESCRIPTION
**Pull request by pine3ree**
###### TODO
- add test case
- merge default params into RouteResult ***DONE

### CODE REVIEW

**Comment by weierophinney** [comment]
@pine3ree — changes look good, but can you provide some unit tests, please?

**Comment by pine3ree** [comment]
@weierophinney 
the simple test case I am trying to add seems to cause conflict with the last merge. Do you want me to open a new PR with all the updates + this simple test case (+ a few more assertions already tested locally that also involve optional parameters and require my previous merged pr)?

kind regards

**Comment by weierophinney** [comment]
@pine3ree Yes, please. Since the last merge is not in a release yet, we're fine in terms of updating test expectations.

**Comment by pine3ree** [comment]
@weierophinney 
Hello, i added #7 as a replacement for this one #5 (I left this one open so that you can copy the labels you assigned).
Please check if the tests I added could be considered sufficient. (btw travis has some kind of issue with the build server, 1 build didn't complete due to network error).

kind regards

**Comment by weierophinney** [comment]
@pine3ree Travis is having network issues currently, which is the source of the build issues you're seeing.

**Pull request closed without merging**
