### PR TITLE
Update Travis CI config

### PR DESCRIPTION
**Pull request by geerteltink**
- Removes irc notifications
- Removes slack notifications
- Removes hhvm
- Adds nightly PHP 7.2 builds
- Update to [latest guidelines](https://github.com/zendframework/maintainers/blob/master/template/.travis.yml)

### CODE REVIEW

**Comment by froschdesign** [comment]
@xtreamwayz 
All these changes maybe fine, but no one can review your PR's, because where is the reference for this? Where can I read which changes are important, which changes should include or not and which file structure is preferred?
I do not mean the Travis documentation, I mean the requirements for all ZF repositories.

It can not be the goal, that only two or three people knows these requirements. Therefore we need a boilerplate for the Travis configuration file _and_ the Composer file.

/cc @weierophinney

**Comment by geerteltink** [comment]
@froschdesign I agree. I've asked for sort of a template as well in the slack contributors channel yesterday.

For notifications: https://zendframework.slackarchive.io/contributors/page-4/ts-1499810981101710
hhmv drop was mentioned in a blog post I think.

**Comment by froschdesign** [comment]
@xtreamwayz 
I know the blog post and I know the discussion on Slack, but this can not be a place for references or informations to contributors and maintainers.

* The blog is good to inform the "outside world".
* Slack and the forum is good for discussions, questions, etc.

But these channels are too fragmented and searching ends in a mess.


We already have a place for this kind of information: 

**Contributors and maintainers information for Zend Framework** (https://github.com/zendframework/maintainers)

Now, we just have to use them!

**Comment by geerteltink** [comment]
For completeness: 

- zendframework/maintainers#15
- zendframework/maintainers#16

**Comment by geerteltink** [comment]
@froschdesign Are these PR's good to merge now?

**Pull request merged**
